// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc.proto

package driver

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Status int32

const (
	Status_Free Status = 0
	Status_Busy Status = 1
)

var Status_name = map[int32]string{
	0: "Free",
	1: "Busy",
}

var Status_value = map[string]int32{
	"Free": 0,
	"Busy": 1,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}

func (Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{0}
}

type TaxiType int32

const (
	TaxiType_Business TaxiType = 0
	TaxiType_Comfort  TaxiType = 1
	TaxiType_Economy  TaxiType = 3
)

var TaxiType_name = map[int32]string{
	0: "Business",
	1: "Comfort",
	3: "Economy",
}

var TaxiType_value = map[string]int32{
	"Business": 0,
	"Comfort":  1,
	"Economy":  3,
}

func (x TaxiType) String() string {
	return proto.EnumName(TaxiType_name, int32(x))
}

func (TaxiType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{1}
}

type DriversPhone struct {
	Phone                string   `protobuf:"bytes,1,opt,name=Phone,proto3" json:"Phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DriversPhone) Reset()         { *m = DriversPhone{} }
func (m *DriversPhone) String() string { return proto.CompactTextString(m) }
func (*DriversPhone) ProtoMessage()    {}
func (*DriversPhone) Descriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{0}
}

func (m *DriversPhone) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DriversPhone.Unmarshal(m, b)
}
func (m *DriversPhone) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DriversPhone.Marshal(b, m, deterministic)
}
func (m *DriversPhone) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DriversPhone.Merge(m, src)
}
func (m *DriversPhone) XXX_Size() int {
	return xxx_messageInfo_DriversPhone.Size(m)
}
func (m *DriversPhone) XXX_DiscardUnknown() {
	xxx_messageInfo_DriversPhone.DiscardUnknown(m)
}

var xxx_messageInfo_DriversPhone proto.InternalMessageInfo

func (m *DriversPhone) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type AllOrders struct {
	Orders               []*Order `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AllOrders) Reset()         { *m = AllOrders{} }
func (m *AllOrders) String() string { return proto.CompactTextString(m) }
func (*AllOrders) ProtoMessage()    {}
func (*AllOrders) Descriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{1}
}

func (m *AllOrders) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllOrders.Unmarshal(m, b)
}
func (m *AllOrders) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllOrders.Marshal(b, m, deterministic)
}
func (m *AllOrders) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllOrders.Merge(m, src)
}
func (m *AllOrders) XXX_Size() int {
	return xxx_messageInfo_AllOrders.Size(m)
}
func (m *AllOrders) XXX_DiscardUnknown() {
	xxx_messageInfo_AllOrders.DiscardUnknown(m)
}

var xxx_messageInfo_AllOrders proto.InternalMessageInfo

func (m *AllOrders) GetOrders() []*Order {
	if m != nil {
		return m.Orders
	}
	return nil
}

type Order struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	UserPhone            string   `protobuf:"bytes,2,opt,name=UserPhone,proto3" json:"UserPhone,omitempty"`
	DriverPhone          string   `protobuf:"bytes,3,opt,name=DriverPhone,proto3" json:"DriverPhone,omitempty"`
	From                 string   `protobuf:"bytes,4,opt,name=From,proto3" json:"From,omitempty"`
	To                   string   `protobuf:"bytes,5,opt,name=To,proto3" json:"To,omitempty"`
	TaxiType             string   `protobuf:"bytes,6,opt,name=TaxiType,proto3" json:"TaxiType,omitempty"`
	Date                 string   `protobuf:"bytes,7,opt,name=Date,proto3" json:"Date,omitempty"`
	Status               string   `protobuf:"bytes,8,opt,name=Status,proto3" json:"Status,omitempty"`
	Rating               int32    `protobuf:"varint,9,opt,name=Rating,proto3" json:"Rating,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{2}
}

func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Order) GetUserPhone() string {
	if m != nil {
		return m.UserPhone
	}
	return ""
}

func (m *Order) GetDriverPhone() string {
	if m != nil {
		return m.DriverPhone
	}
	return ""
}

func (m *Order) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *Order) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *Order) GetTaxiType() string {
	if m != nil {
		return m.TaxiType
	}
	return ""
}

func (m *Order) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func (m *Order) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Order) GetRating() int32 {
	if m != nil {
		return m.Rating
	}
	return 0
}

type Address struct {
	Lat                  float32  `protobuf:"fixed32,1,opt,name=Lat,proto3" json:"Lat,omitempty"`
	Lng                  float32  `protobuf:"fixed32,2,opt,name=Lng,proto3" json:"Lng,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Address) Reset()         { *m = Address{} }
func (m *Address) String() string { return proto.CompactTextString(m) }
func (*Address) ProtoMessage()    {}
func (*Address) Descriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{3}
}

func (m *Address) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Address.Unmarshal(m, b)
}
func (m *Address) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Address.Marshal(b, m, deterministic)
}
func (m *Address) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Address.Merge(m, src)
}
func (m *Address) XXX_Size() int {
	return xxx_messageInfo_Address.Size(m)
}
func (m *Address) XXX_DiscardUnknown() {
	xxx_messageInfo_Address.DiscardUnknown(m)
}

var xxx_messageInfo_Address proto.InternalMessageInfo

func (m *Address) GetLat() float32 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *Address) GetLng() float32 {
	if m != nil {
		return m.Lng
	}
	return 0
}

type Driver struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Phone                string   `protobuf:"bytes,2,opt,name=Phone,proto3" json:"Phone,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=Email,proto3" json:"Email,omitempty"`
	TaxiType             string   `protobuf:"bytes,4,opt,name=TaxiType,proto3" json:"TaxiType,omitempty"`
	Status               string   `protobuf:"bytes,5,opt,name=Status,proto3" json:"Status,omitempty"`
	Rating               int32    `protobuf:"varint,6,opt,name=Rating,proto3" json:"Rating,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Driver) Reset()         { *m = Driver{} }
func (m *Driver) String() string { return proto.CompactTextString(m) }
func (*Driver) ProtoMessage()    {}
func (*Driver) Descriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{4}
}

func (m *Driver) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Driver.Unmarshal(m, b)
}
func (m *Driver) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Driver.Marshal(b, m, deterministic)
}
func (m *Driver) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Driver.Merge(m, src)
}
func (m *Driver) XXX_Size() int {
	return xxx_messageInfo_Driver.Size(m)
}
func (m *Driver) XXX_DiscardUnknown() {
	xxx_messageInfo_Driver.DiscardUnknown(m)
}

var xxx_messageInfo_Driver proto.InternalMessageInfo

func (m *Driver) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Driver) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *Driver) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Driver) GetTaxiType() string {
	if m != nil {
		return m.TaxiType
	}
	return ""
}

func (m *Driver) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Driver) GetRating() int32 {
	if m != nil {
		return m.Rating
	}
	return 0
}

type Error struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{5}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type AllDrivers struct {
	Drivers              []*Driver `protobuf:"bytes,1,rep,name=drivers,proto3" json:"drivers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AllDrivers) Reset()         { *m = AllDrivers{} }
func (m *AllDrivers) String() string { return proto.CompactTextString(m) }
func (*AllDrivers) ProtoMessage()    {}
func (*AllDrivers) Descriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{6}
}

func (m *AllDrivers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllDrivers.Unmarshal(m, b)
}
func (m *AllDrivers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllDrivers.Marshal(b, m, deterministic)
}
func (m *AllDrivers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllDrivers.Merge(m, src)
}
func (m *AllDrivers) XXX_Size() int {
	return xxx_messageInfo_AllDrivers.Size(m)
}
func (m *AllDrivers) XXX_DiscardUnknown() {
	xxx_messageInfo_AllDrivers.DiscardUnknown(m)
}

var xxx_messageInfo_AllDrivers proto.InternalMessageInfo

func (m *AllDrivers) GetDrivers() []*Driver {
	if m != nil {
		return m.Drivers
	}
	return nil
}

type RateTripByDriverRequest struct {
	Rate                 int32    `protobuf:"varint,1,opt,name=Rate,proto3" json:"Rate,omitempty"`
	Phone                string   `protobuf:"bytes,2,opt,name=Phone,proto3" json:"Phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RateTripByDriverRequest) Reset()         { *m = RateTripByDriverRequest{} }
func (m *RateTripByDriverRequest) String() string { return proto.CompactTextString(m) }
func (*RateTripByDriverRequest) ProtoMessage()    {}
func (*RateTripByDriverRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{7}
}

func (m *RateTripByDriverRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RateTripByDriverRequest.Unmarshal(m, b)
}
func (m *RateTripByDriverRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RateTripByDriverRequest.Marshal(b, m, deterministic)
}
func (m *RateTripByDriverRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RateTripByDriverRequest.Merge(m, src)
}
func (m *RateTripByDriverRequest) XXX_Size() int {
	return xxx_messageInfo_RateTripByDriverRequest.Size(m)
}
func (m *RateTripByDriverRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RateTripByDriverRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RateTripByDriverRequest proto.InternalMessageInfo

func (m *RateTripByDriverRequest) GetRate() int32 {
	if m != nil {
		return m.Rate
	}
	return 0
}

func (m *RateTripByDriverRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type Request struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{8}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

type AllFreeDrivers struct {
	Drivers              []*Driver `protobuf:"bytes,1,rep,name=drivers,proto3" json:"drivers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AllFreeDrivers) Reset()         { *m = AllFreeDrivers{} }
func (m *AllFreeDrivers) String() string { return proto.CompactTextString(m) }
func (*AllFreeDrivers) ProtoMessage()    {}
func (*AllFreeDrivers) Descriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{9}
}

func (m *AllFreeDrivers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllFreeDrivers.Unmarshal(m, b)
}
func (m *AllFreeDrivers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllFreeDrivers.Marshal(b, m, deterministic)
}
func (m *AllFreeDrivers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllFreeDrivers.Merge(m, src)
}
func (m *AllFreeDrivers) XXX_Size() int {
	return xxx_messageInfo_AllFreeDrivers.Size(m)
}
func (m *AllFreeDrivers) XXX_DiscardUnknown() {
	xxx_messageInfo_AllFreeDrivers.DiscardUnknown(m)
}

var xxx_messageInfo_AllFreeDrivers proto.InternalMessageInfo

func (m *AllFreeDrivers) GetDrivers() []*Driver {
	if m != nil {
		return m.Drivers
	}
	return nil
}

type RateResponse struct {
	Answer               string   `protobuf:"bytes,1,opt,name=Answer,proto3" json:"Answer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RateResponse) Reset()         { *m = RateResponse{} }
func (m *RateResponse) String() string { return proto.CompactTextString(m) }
func (*RateResponse) ProtoMessage()    {}
func (*RateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{10}
}

func (m *RateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RateResponse.Unmarshal(m, b)
}
func (m *RateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RateResponse.Marshal(b, m, deterministic)
}
func (m *RateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RateResponse.Merge(m, src)
}
func (m *RateResponse) XXX_Size() int {
	return xxx_messageInfo_RateResponse.Size(m)
}
func (m *RateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RateResponse proto.InternalMessageInfo

func (m *RateResponse) GetAnswer() string {
	if m != nil {
		return m.Answer
	}
	return ""
}

type OrderRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	From                 string   `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To                   string   `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderRequest) Reset()         { *m = OrderRequest{} }
func (m *OrderRequest) String() string { return proto.CompactTextString(m) }
func (*OrderRequest) ProtoMessage()    {}
func (*OrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{11}
}

func (m *OrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderRequest.Unmarshal(m, b)
}
func (m *OrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderRequest.Marshal(b, m, deterministic)
}
func (m *OrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderRequest.Merge(m, src)
}
func (m *OrderRequest) XXX_Size() int {
	return xxx_messageInfo_OrderRequest.Size(m)
}
func (m *OrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OrderRequest proto.InternalMessageInfo

func (m *OrderRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *OrderRequest) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *OrderRequest) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

type ListOfOrders struct {
	Orders               []*Order `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListOfOrders) Reset()         { *m = ListOfOrders{} }
func (m *ListOfOrders) String() string { return proto.CompactTextString(m) }
func (*ListOfOrders) ProtoMessage()    {}
func (*ListOfOrders) Descriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{12}
}

func (m *ListOfOrders) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListOfOrders.Unmarshal(m, b)
}
func (m *ListOfOrders) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListOfOrders.Marshal(b, m, deterministic)
}
func (m *ListOfOrders) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListOfOrders.Merge(m, src)
}
func (m *ListOfOrders) XXX_Size() int {
	return xxx_messageInfo_ListOfOrders.Size(m)
}
func (m *ListOfOrders) XXX_DiscardUnknown() {
	xxx_messageInfo_ListOfOrders.DiscardUnknown(m)
}

var xxx_messageInfo_ListOfOrders proto.InternalMessageInfo

func (m *ListOfOrders) GetOrders() []*Order {
	if m != nil {
		return m.Orders
	}
	return nil
}

type OrderResult struct {
	Order                *Order   `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderResult) Reset()         { *m = OrderResult{} }
func (m *OrderResult) String() string { return proto.CompactTextString(m) }
func (*OrderResult) ProtoMessage()    {}
func (*OrderResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{13}
}

func (m *OrderResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderResult.Unmarshal(m, b)
}
func (m *OrderResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderResult.Marshal(b, m, deterministic)
}
func (m *OrderResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderResult.Merge(m, src)
}
func (m *OrderResult) XXX_Size() int {
	return xxx_messageInfo_OrderResult.Size(m)
}
func (m *OrderResult) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderResult.DiscardUnknown(m)
}

var xxx_messageInfo_OrderResult proto.InternalMessageInfo

func (m *OrderResult) GetOrder() *Order {
	if m != nil {
		return m.Order
	}
	return nil
}

type RateTripByUserRequest struct {
	Rate                 int32    `protobuf:"varint,1,opt,name=Rate,proto3" json:"Rate,omitempty"`
	Phone                string   `protobuf:"bytes,2,opt,name=Phone,proto3" json:"Phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RateTripByUserRequest) Reset()         { *m = RateTripByUserRequest{} }
func (m *RateTripByUserRequest) String() string { return proto.CompactTextString(m) }
func (*RateTripByUserRequest) ProtoMessage()    {}
func (*RateTripByUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{14}
}

func (m *RateTripByUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RateTripByUserRequest.Unmarshal(m, b)
}
func (m *RateTripByUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RateTripByUserRequest.Marshal(b, m, deterministic)
}
func (m *RateTripByUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RateTripByUserRequest.Merge(m, src)
}
func (m *RateTripByUserRequest) XXX_Size() int {
	return xxx_messageInfo_RateTripByUserRequest.Size(m)
}
func (m *RateTripByUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RateTripByUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RateTripByUserRequest proto.InternalMessageInfo

func (m *RateTripByUserRequest) GetRate() int32 {
	if m != nil {
		return m.Rate
	}
	return 0
}

func (m *RateTripByUserRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Phone                string   `protobuf:"bytes,3,opt,name=Phone,proto3" json:"Phone,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=Email,proto3" json:"Email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{15}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func init() {
	proto.RegisterEnum("api.Status", Status_name, Status_value)
	proto.RegisterEnum("api.TaxiType", TaxiType_name, TaxiType_value)
	proto.RegisterType((*DriversPhone)(nil), "api.DriversPhone")
	proto.RegisterType((*AllOrders)(nil), "api.AllOrders")
	proto.RegisterType((*Order)(nil), "api.Order")
	proto.RegisterType((*Address)(nil), "api.Address")
	proto.RegisterType((*Driver)(nil), "api.driver")
	proto.RegisterType((*Error)(nil), "api.Error")
	proto.RegisterType((*AllDrivers)(nil), "api.AllDrivers")
	proto.RegisterType((*RateTripByDriverRequest)(nil), "api.RateTripByDriverRequest")
	proto.RegisterType((*Request)(nil), "api.Request")
	proto.RegisterType((*AllFreeDrivers)(nil), "api.AllFreeDrivers")
	proto.RegisterType((*RateResponse)(nil), "api.RateResponse")
	proto.RegisterType((*OrderRequest)(nil), "api.OrderRequest")
	proto.RegisterType((*ListOfOrders)(nil), "api.ListOfOrders")
	proto.RegisterType((*OrderResult)(nil), "api.OrderResult")
	proto.RegisterType((*RateTripByUserRequest)(nil), "api.RateTripByUserRequest")
	proto.RegisterType((*User)(nil), "api.user")
}

func init() { proto.RegisterFile("grpc.proto", fileDescriptor_bedfbfc9b54e5600) }

var fileDescriptor_bedfbfc9b54e5600 = []byte{
	// 728 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x55, 0xdd, 0x6e, 0xd3, 0x30,
	0x14, 0x6e, 0xda, 0xa6, 0x3f, 0x27, 0xdd, 0x96, 0x99, 0x01, 0x51, 0x35, 0xa4, 0x62, 0x01, 0x9a,
	0x26, 0xb1, 0xa1, 0xee, 0x02, 0x10, 0x12, 0xa8, 0xdd, 0x9f, 0x26, 0x4d, 0x0c, 0xb2, 0xc2, 0x05,
	0x77, 0x61, 0x75, 0x4b, 0xa4, 0x34, 0x0e, 0xb6, 0x3b, 0xe8, 0x5b, 0xf0, 0x42, 0x3c, 0x09, 0x2f,
	0xc2, 0x25, 0xf2, 0xb1, 0xb3, 0xa6, 0x5d, 0xb9, 0xd8, 0xdd, 0xf9, 0xf1, 0xf1, 0x39, 0xdf, 0x77,
	0x3e, 0x27, 0x00, 0x63, 0x91, 0x5d, 0xed, 0x65, 0x82, 0x2b, 0x4e, 0x2a, 0x51, 0x16, 0xd3, 0x27,
	0xd0, 0x3a, 0x12, 0xf1, 0x35, 0x13, 0xf2, 0xc3, 0x37, 0x9e, 0x32, 0xb2, 0x05, 0x2e, 0x1a, 0x81,
	0xd3, 0x71, 0x76, 0x9a, 0xa1, 0x71, 0xe8, 0x3e, 0x34, 0x7b, 0x49, 0x72, 0x21, 0x86, 0x4c, 0x48,
	0x42, 0xa1, 0xc6, 0xd1, 0x0a, 0x9c, 0x4e, 0x65, 0xc7, 0xeb, 0xc2, 0x5e, 0x94, 0xc5, 0x7b, 0x98,
	0x0c, 0x6d, 0x86, 0xfe, 0x71, 0xc0, 0xc5, 0x08, 0x59, 0x87, 0xf2, 0xd9, 0xd0, 0xde, 0x56, 0x3e,
	0x1b, 0x92, 0x6d, 0x68, 0x7e, 0x92, 0x4c, 0x98, 0x26, 0x65, 0x0c, 0xcf, 0x03, 0xa4, 0x03, 0x9e,
	0x19, 0xc7, 0xe4, 0x2b, 0x98, 0x2f, 0x86, 0x08, 0x81, 0xea, 0x89, 0xe0, 0x93, 0xa0, 0x8a, 0x29,
	0xb4, 0x75, 0x8f, 0x01, 0x0f, 0x5c, 0xd3, 0x63, 0xc0, 0x49, 0x1b, 0x1a, 0x83, 0xe8, 0x67, 0x3c,
	0x98, 0x65, 0x2c, 0xa8, 0x61, 0xf4, 0xc6, 0xd7, 0xf5, 0x47, 0x91, 0x62, 0x41, 0xdd, 0xd4, 0x6b,
	0x9b, 0x3c, 0x80, 0xda, 0xa5, 0x8a, 0xd4, 0x54, 0x06, 0x0d, 0x8c, 0x5a, 0x4f, 0xc7, 0xc3, 0x48,
	0xc5, 0xe9, 0x38, 0x68, 0x76, 0x9c, 0x1d, 0x37, 0xb4, 0x1e, 0x7d, 0x0e, 0xf5, 0xde, 0x70, 0x28,
	0x98, 0x94, 0xc4, 0x87, 0xca, 0x79, 0xa4, 0x10, 0x5f, 0x39, 0xd4, 0x26, 0x46, 0xd2, 0x31, 0x42,
	0xd3, 0x91, 0x74, 0x4c, 0x7f, 0x39, 0x50, 0x33, 0x10, 0x6e, 0xb1, 0x71, 0x43, 0x77, 0xb9, 0x40,
	0xb7, 0x8e, 0x1e, 0x4f, 0xa2, 0x38, 0xb1, 0xf8, 0x8d, 0xb3, 0x80, 0xaa, 0xba, 0x84, 0x6a, 0x8e,
	0xc0, 0xfd, 0x0f, 0x82, 0xda, 0x02, 0x82, 0xc7, 0xe0, 0x1e, 0x0b, 0xc1, 0x05, 0x09, 0xa0, 0x3e,
	0x61, 0x52, 0x46, 0xe3, 0x7c, 0xe3, 0xb9, 0x4b, 0x0f, 0x00, 0x7a, 0x49, 0x62, 0xc5, 0x41, 0x9e,
	0x42, 0x7d, 0x68, 0x4c, 0xbb, 0x75, 0x0f, 0xb7, 0x6e, 0xd2, 0x61, 0x9e, 0xa3, 0x87, 0xf0, 0x30,
	0x8c, 0x14, 0x1b, 0x88, 0x38, 0xeb, 0xcf, 0x6c, 0x92, 0x7d, 0x9f, 0x32, 0xa9, 0x34, 0xf1, 0x3a,
	0x85, 0x6d, 0xdc, 0x10, 0xed, 0xd5, 0xf0, 0x69, 0x13, 0xea, 0xb6, 0x88, 0xbe, 0x84, 0xf5, 0x5e,
	0x92, 0x9c, 0x08, 0xc6, 0xee, 0x38, 0xc8, 0x33, 0x68, 0xe9, 0x0e, 0x21, 0x93, 0x19, 0x4f, 0x25,
	0x12, 0xd4, 0x4b, 0xe5, 0x0f, 0x26, 0x2c, 0x4c, 0xeb, 0xd1, 0x8f, 0xd0, 0x32, 0xca, 0xb5, 0x53,
	0x3e, 0x82, 0xea, 0x54, 0xda, 0x53, 0x5e, 0xb7, 0x89, 0x77, 0x6b, 0x79, 0x86, 0x18, 0xd6, 0x20,
	0x46, 0x5a, 0x7d, 0x66, 0x5e, 0xb4, 0xf5, 0x4e, 0x15, 0xb7, 0xab, 0x2a, 0x2b, 0x4e, 0xbb, 0xd0,
	0x3a, 0x8f, 0xa5, 0xba, 0x18, 0xdd, 0xe1, 0xbd, 0xec, 0x83, 0x67, 0xc7, 0x90, 0xd3, 0x44, 0x91,
	0x0e, 0xb8, 0x98, 0xb0, 0x63, 0x14, 0x2b, 0x4c, 0x82, 0xf6, 0xe0, 0xfe, 0x9c, 0x68, 0x1c, 0xf0,
	0xce, 0x34, 0x7f, 0x86, 0xaa, 0x2e, 0xbc, 0xa5, 0x49, 0x02, 0xd5, 0xf7, 0xd1, 0x24, 0x3f, 0x8c,
	0xf6, 0xfc, 0x86, 0xca, 0x4a, 0x9d, 0x56, 0x0b, 0x3a, 0xdd, 0xdd, 0xce, 0xb5, 0x48, 0x1a, 0xfa,
	0xad, 0x32, 0xe6, 0x97, 0xb4, 0xd5, 0x9f, 0xca, 0x99, 0xef, 0xec, 0x76, 0xe7, 0x2a, 0x26, 0x2d,
	0x68, 0xf4, 0xa7, 0x32, 0x4e, 0x99, 0x94, 0x7e, 0x89, 0x78, 0x50, 0x3f, 0xe4, 0x93, 0x11, 0x17,
	0xca, 0x77, 0xb4, 0x73, 0x7c, 0xc5, 0x53, 0x3e, 0x99, 0xf9, 0x95, 0xee, 0x6f, 0x07, 0x3c, 0x3d,
	0xea, 0x25, 0x13, 0xd7, 0xf1, 0x15, 0x23, 0x5d, 0x68, 0x22, 0x19, 0xfa, 0x22, 0xb2, 0x59, 0x20,
	0xc7, 0x70, 0xd0, 0xf6, 0x8b, 0x21, 0x4d, 0x28, 0x2d, 0x91, 0xd7, 0xb0, 0x71, 0xca, 0x94, 0x59,
	0x89, 0x61, 0x6c, 0x55, 0xa5, 0x09, 0x15, 0xd7, 0x47, 0x4b, 0xe4, 0x9d, 0xd1, 0xd2, 0x79, 0x24,
	0x95, 0xe6, 0x9b, 0xb4, 0xf1, 0xd0, 0x4a, 0xfa, 0xed, 0x05, 0x45, 0xe9, 0xd1, 0x52, 0xf7, 0xaf,
	0x03, 0x6b, 0x46, 0xa0, 0x39, 0x82, 0x57, 0xb0, 0x79, 0xca, 0xd4, 0x92, 0xb4, 0x5b, 0xa6, 0xd6,
	0xde, 0x74, 0x0f, 0xbd, 0xc5, 0x23, 0xb4, 0x44, 0x5e, 0xc0, 0x9a, 0xa9, 0x5c, 0x5d, 0xb5, 0x91,
	0x57, 0xcd, 0x2b, 0xde, 0x82, 0xbf, 0xfc, 0x26, 0xc9, 0xf6, 0x12, 0x84, 0x85, 0xa7, 0xda, 0x36,
	0x7a, 0xc3, 0x0f, 0x04, 0x2d, 0x91, 0x37, 0xb0, 0x65, 0x3a, 0x1a, 0x42, 0x2e, 0x46, 0xf6, 0x8e,
	0xcd, 0xc2, 0xc3, 0x33, 0x7f, 0x8f, 0xf6, 0x7a, 0xde, 0x3d, 0xe7, 0xae, 0xbf, 0xf6, 0xc5, 0xd3,
	0xbf, 0x9c, 0x7d, 0xf3, 0x2e, 0xbf, 0xd6, 0xf0, 0xd7, 0x73, 0xf0, 0x2f, 0x00, 0x00, 0xff, 0xff,
	0x4e, 0x8c, 0xbc, 0xbd, 0x88, 0x06, 0x00, 0x00,
}
